name: Build Debian package on release

on:
  push:
    branches: [ feat-create-debian-package-with-tag ]
    paths-ignore:
      - 'docs_src/**'
      - 'README.md'
      - 'CITATION'
      - 'book.toml'
      - 'CONTRIBUTING.md'
    tags: [ 'v*.*.*', 'dev*.*.*' ]
  workflow_dispatch:


jobs:
  create_debian_pkg_with_tag:
    name: Create Debian package associated to version tag
    runs-on: ubuntu-latest
    steps:
    - name: debug version env variable name
      run: echo "${{ GITHUB_REF }}"
    - name: Checkout scaphandre-debian repository
      uses: actions/checkout@v4
      with:
        repository: barnumbirr/scaphandre-debian
    - name: Build package with version tag and Debian 11 Bullseye
      run : |
        ./build.sh -v ${{ GITHUB_REF }}
    - name: Build package with version tag and Debian 12 Bookworm
      run: |
        ./build.sh -i debian:bookworm-slim -v ${{ GITHUB_REF }}
